# Generated by Django 6.0.1 on 2026-02-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='claim_id',
            field=models.CharField(default='TEMP-CLAIM-001', help_text='Unique Claim ID from source system', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='insurance_provider',
            field=models.CharField(help_text='Payer', max_length=100),
        ),
    ]
