# Generated by Django 6.0.1 on 2026-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_job_claim_id_job_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('operations_manager', 'Operations Manager'), ('billing', 'Billing Staff'), ('payment', 'Payment Posting Staff'), ('ar_denial', 'AR / Denial Staff')], default='billing', max_length=20),
        ),
    ]
