# Generated by Django 4.2.28 on 2026-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_user_user_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Operational Notes/Procedural Narrative', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Captured tactical metadata from Ingestion Bay'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid_full', 'Paid in Full'), ('paid_partial', 'Paid Partial'), ('denied', 'Denied'), ('denial_management', 'Denial Management'), ('ar_followup', 'AR Follow-up'), ('closed_paid', 'Closed - Paid'), ('closed_adjusted', 'Closed - Adjusted'), ('on_hold', 'On Hold'), ('escalated', 'Escalated'), ('appeal_in_progress', 'Appeal in Progress'), ('written_off', 'Written Off'), ('dismissed', 'Dismissed')], default='draft', max_length=30),
        ),
    ]
